---
title: "Data analysis for beginners in R"
subtitle: "Course overview"
author: "Hannah Metzler"
date: "March 6 2023"
format: revealjs
editor: visual
---

# Who am I?

-   PostDoc at MedUni Vienna and the Complexity Science Hub
-   Psychology, Neuroscience, Data Science

# Intention

-   For beginners
-   Encourage you to start writing your analyses as code
-   Reproducibility & transparency for yourself and others
-   Welcome to all your doubts and questions!
-   Break things down to lower the barrier.
-   Please interrupt any time and ask questions!

# Course overview

-   Wednesdays 10am-12pm: March 6, 13, 20 & 27, 2024
-   Time schedule: Break from 11h to 11h10
-   All materials: <https://hannahmetzler.eu/R_intro/> or <https://github.com/hannahmetzler/R_intro/>
-   Lesson 1: Getting started
-   Later lessons: Data visualizations, data wrangling, basic statistics
-   If time: Github & Markdown (Quarto) reports

# Before we start

-   Have all of you managed to install R & Rstudio?
-   How do you feel about learning R in one word?
    -   Shy/excited/under-confident/brave/bored?
-   Previous experience?
    -   none/very little/little?

# To follow the course

-   Open R studio
-   Open Lesson 1 on the side
-   Write code yourself as we go along to practice.
    -   Code fields from materials can be copied by click
